FROM node:18-alpine AS deps
WORKDIR /app
COPY apps/backend/package*.json ./
RUN npm ci --production --silent

FROM node:18-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY apps/backend .
RUN npm run build

FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/.next .next
COPY --from=builder /app/node_modules ./node_modules
COPY apps/backend/package*.json ./
EXPOSE 3001
CMD ["npm", "start"]
